// AUTO-GENERATED from src/content/blog/*.json — do not edit by hand.
// See docs/product/content-migration-reconciliation.md
export type BlogEntryMeta = {
  slug: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  publishedAt?: string;
  updatedAt?: string;
  author: string;
  heroImage?: string;
};

export const BLOG_CATEGORIES: string[] = [
  "AI & Automation",
  "Candidate Experience",
  "Career Development",
  "Compensation",
  "Compliance",
  "Diversity & Inclusion",
  "Hiring Metrics",
  "Industry: Accounting",
  "Industry: Climate Tech",
  "Industry: Healthcare",
  "Industry: SaaS",
  "Industry: Sales",
  "Industry: Skilled Trades",
  "Interviewing",
  "Leadership",
  "Onboarding",
  "Remote & Distributed",
  "Retention & Culture",
  "Skills & Assessment",
  "Talent Strategy",
  "Tools & Tech",
];

export const BLOG_CATEGORY_SLUGS: Record<string, string> = {
  "AI & Automation": "ai-automation",
  "Candidate Experience": "candidate-experience",
  "Career Development": "career-development",
  "Compensation": "compensation",
  "Compliance": "compliance",
  "Diversity & Inclusion": "diversity-inclusion",
  "Hiring Metrics": "hiring-metrics",
  "Industry: Accounting": "industry-accounting",
  "Industry: Climate Tech": "industry-climate-tech",
  "Industry: Healthcare": "industry-healthcare",
  "Industry: SaaS": "industry-saas",
  "Industry: Sales": "industry-sales",
  "Industry: Skilled Trades": "industry-skilled-trades",
  "Interviewing": "interviewing",
  "Leadership": "leadership",
  "Onboarding": "onboarding",
  "Remote & Distributed": "remote-distributed",
  "Retention & Culture": "retention-culture",
  "Skills & Assessment": "skills-assessment",
  "Talent Strategy": "talent-strategy",
  "Tools & Tech": "tools-tech",
};

export const BLOG_CATEGORY_BY_SLUG: Record<string, string> = {
  "ai-automation": "AI & Automation",
  "candidate-experience": "Candidate Experience",
  "career-development": "Career Development",
  "compensation": "Compensation",
  "compliance": "Compliance",
  "diversity-inclusion": "Diversity & Inclusion",
  "hiring-metrics": "Hiring Metrics",
  "industry-accounting": "Industry: Accounting",
  "industry-climate-tech": "Industry: Climate Tech",
  "industry-healthcare": "Industry: Healthcare",
  "industry-saas": "Industry: SaaS",
  "industry-sales": "Industry: Sales",
  "industry-skilled-trades": "Industry: Skilled Trades",
  "interviewing": "Interviewing",
  "leadership": "Leadership",
  "onboarding": "Onboarding",
  "remote-distributed": "Remote & Distributed",
  "retention-culture": "Retention & Culture",
  "skills-assessment": "Skills & Assessment",
  "talent-strategy": "Talent Strategy",
  "tools-tech": "Tools & Tech",
};

export const INCLUDED_BLOG_SLUGS: readonly string[] = [
  "30-60-90-onboarding-plan-2026",
  "accounting-firm-recruitment-strategies",
  "accounting-talent-shortage-big-four",
  "accounting-talent-shortage-guide",
  "accounting-talent-shortage-solutions",
  "ai-impact-on-jobs-hiring",
  "ai-in-recruitment",
  "ai-ml-engineering-hiring-guide",
  "ai-replacing-vs-augmenting-recruiters",
  "ai-reshaping-every-industry-hiring",
  "ai-screening-ethics",
  "ai-workforce-planning-2030",
  "ambient-computing-workplace-transformation",
  "ats-implementation-guide",
  "ats-optimization-guide",
  "background-check-best-practices",
  "behavioral-health-hiring-challenges",
  "behavioral-interview-guide-employers",
  "biotech-startup-hiring-strategy",
  "blockchain-credentials-hiring",
  "boomerang-employees",
  "building-high-performance-culture-remotely",
  "building-high-performance-teams",
  "building-talent-pipeline",
  "candidate-communication-cadence",
  "candidate-experience-audit-checklist",
  "candidate-experience-competitive-weapon",
  "candidate-experience-matters",
  "candidate-experience-optimization",
  "candidate-ghosting-prevention",
  "career-change-guide-professionals",
  "career-pathing-employee-retention",
  "career-pivot-guide-professionals",
  "ceo-guide-talent-strategy",
  "chief-of-staff-role-guide",
  "chief-people-officer-evolution",
  "reducing-cost-per-hire",
  "reducing-time-to-hire-without-sacrificing-quality",
  "reference-check-mastery",
  "rejection-with-grace",
  "remote-first-compensation-guide",
  "remote-hiring-best-practices",
  "remote-hiring-best-practices-2026",
  "remote-interview-best-practices",
  "remote-vs-hybrid-talent-strategy",
  "renewable-energy-talent-hiring",
  "retention-economics-guide",
  "return-to-office-hiring",
  "return-to-office-talent-impact",
  "revenue-operations-role-breakdown",
  "saas-engineering-team-scaling",
  "saas-go-to-market-hiring",
  "saas-go-to-market-hiring-guide",
  "salary-compression-guide",
  "salary-negotiation-from-employer-perspective",
  "salary-negotiation-masterclass",
  "salary-trends-2026-comprehensive",
  "sales-hiring-playbook",
  "sales-leadership-hiring",
  "sales-leadership-hiring-playbook",
  "sales-team-building-guide",
  "sdr-bdr-hiring-scaling-guide",
  "sdr-hiring-at-scale",
  "sdr-hiring-at-scale-2026",
  "second-chance-hiring-guide",
  "series-a-gtm-team-building",
  "skilled-trades-hiring-crisis",
  "skills-based-hiring-implementation",
  "skills-based-hiring-revolution",
  "skills-based-organizations-future",
  "skills-gap-analysis-guide",
  "skills-taxonomy-building-guide",
] as const;

export const BLOG_METADATA: Record<string, { category: string; tags: string[] }> = {
  "30-60-90-onboarding-plan-2026": { category: "Onboarding", tags: ["onboarding", "2026", "plan"] },
  "accounting-firm-recruitment-strategies": { category: "Industry: Accounting", tags: ["accounting", "recruitment", "strategies", "firm"] },
  "accounting-talent-shortage-big-four": { category: "Industry: Accounting", tags: ["accounting", "four", "shortage", "big", "talent"] },
  "accounting-talent-shortage-guide": { category: "Industry: Accounting", tags: ["accounting", "guide", "talent", "shortage"] },
  "accounting-talent-shortage-solutions": { category: "Industry: Accounting", tags: ["accounting", "solutions", "talent", "shortage"] },
  "ai-impact-on-jobs-hiring": { category: "AI & Automation", tags: ["impact", "jobs", "hiring"] },
  "ai-in-recruitment": { category: "AI & Automation", tags: ["recruitment"] },
  "ai-ml-engineering-hiring-guide": { category: "AI & Automation", tags: ["engineering", "guide", "hiring"] },
  "ai-replacing-vs-augmenting-recruiters": { category: "AI & Automation", tags: ["replacing", "recruiters", "augmenting"] },
  "ai-reshaping-every-industry-hiring": { category: "AI & Automation", tags: ["every", "industry", "reshaping", "hiring"] },
  "ai-screening-ethics": { category: "AI & Automation", tags: ["ethics", "screening"] },
  "ai-workforce-planning-2030": { category: "AI & Automation", tags: ["workforce", "2030", "planning"] },
  "ambient-computing-workplace-transformation": { category: "Tools & Tech", tags: ["ambient", "transformation", "computing", "workplace"] },
  "ats-implementation-guide": { category: "Tools & Tech", tags: ["implementation", "ats", "guide"] },
  "ats-optimization-guide": { category: "Tools & Tech", tags: ["guide", "ats", "optimization"] },
  "background-check-best-practices": { category: "Compliance", tags: ["best", "practices", "check", "background"] },
  "behavioral-health-hiring-challenges": { category: "Industry: Healthcare", tags: ["health", "challenges", "behavioral", "hiring"] },
  "behavioral-interview-guide-employers": { category: "Interviewing", tags: ["interview", "employers", "guide", "behavioral"] },
  "biotech-startup-hiring-strategy": { category: "Industry: Healthcare", tags: ["biotech", "startup", "strategy", "hiring"] },
  "blockchain-credentials-hiring": { category: "Tools & Tech", tags: ["blockchain", "credentials", "hiring"] },
  "boomerang-employees": { category: "Retention & Culture", tags: ["employees", "boomerang"] },
  "building-high-performance-culture-remotely": { category: "Talent Strategy", tags: ["building", "remotely", "performance", "high", "culture"] },
  "building-high-performance-teams": { category: "Talent Strategy", tags: ["teams", "performance", "high", "building"] },
  "building-talent-pipeline": { category: "Talent Strategy", tags: ["pipeline", "talent", "building"] },
  "candidate-communication-cadence": { category: "Candidate Experience", tags: ["cadence", "candidate", "communication"] },
  "candidate-experience-audit-checklist": { category: "Candidate Experience", tags: ["experience", "candidate", "audit", "checklist"] },
  "candidate-experience-competitive-weapon": { category: "Candidate Experience", tags: ["experience", "candidate", "weapon", "competitive"] },
  "candidate-experience-matters": { category: "Candidate Experience", tags: ["experience", "candidate", "matters"] },
  "candidate-experience-optimization": { category: "Candidate Experience", tags: ["experience", "candidate", "optimization"] },
  "candidate-ghosting-prevention": { category: "Candidate Experience", tags: ["prevention", "candidate", "ghosting"] },
  "career-change-guide-professionals": { category: "Career Development", tags: ["guide", "career", "professionals", "change"] },
  "career-pathing-employee-retention": { category: "Retention & Culture", tags: ["retention", "pathing", "career", "employee"] },
  "career-pivot-guide-professionals": { category: "Career Development", tags: ["guide", "career", "professionals", "pivot"] },
  "ceo-guide-talent-strategy": { category: "Leadership", tags: ["ceo", "strategy", "guide", "talent"] },
  "chief-of-staff-role-guide": { category: "Leadership", tags: ["guide", "role", "staff", "chief"] },
  "chief-people-officer-evolution": { category: "Leadership", tags: ["officer", "evolution", "chief", "people"] },
  "reducing-cost-per-hire": { category: "Hiring Metrics", tags: ["hire", "cost", "reducing", "per"] },
  "reducing-time-to-hire-without-sacrificing-quality": { category: "Hiring Metrics", tags: ["sacrificing", "time", "without", "reducing", "hire"] },
  "reference-check-mastery": { category: "Interviewing", tags: ["reference", "mastery", "check"] },
  "rejection-with-grace": { category: "Candidate Experience", tags: ["rejection", "grace", "with"] },
  "remote-first-compensation-guide": { category: "Remote & Distributed", tags: ["compensation", "guide", "remote", "first"] },
  "remote-hiring-best-practices": { category: "Remote & Distributed", tags: ["practices", "best", "remote", "hiring"] },
  "remote-hiring-best-practices-2026": { category: "Remote & Distributed", tags: ["best", "remote", "hiring", "practices", "2026"] },
  "remote-interview-best-practices": { category: "Remote & Distributed", tags: ["interview", "best", "practices", "remote"] },
  "remote-vs-hybrid-talent-strategy": { category: "Remote & Distributed", tags: ["talent", "strategy", "remote", "hybrid"] },
  "renewable-energy-talent-hiring": { category: "Industry: Climate Tech", tags: ["energy", "renewable", "talent", "hiring"] },
  "retention-economics-guide": { category: "Retention & Culture", tags: ["guide", "economics", "retention"] },
  "return-to-office-hiring": { category: "Remote & Distributed", tags: ["return", "office", "hiring"] },
  "return-to-office-talent-impact": { category: "Remote & Distributed", tags: ["return", "impact", "talent", "office"] },
  "revenue-operations-role-breakdown": { category: "Industry: Sales", tags: ["operations", "role", "revenue", "breakdown"] },
  "saas-engineering-team-scaling": { category: "Industry: SaaS", tags: ["scaling", "engineering", "team", "saas"] },
  "saas-go-to-market-hiring": { category: "Industry: SaaS", tags: ["market", "saas", "hiring"] },
  "saas-go-to-market-hiring-guide": { category: "Industry: SaaS", tags: ["market", "guide", "saas", "hiring"] },
  "salary-compression-guide": { category: "Compensation", tags: ["compression", "guide", "salary"] },
  "salary-negotiation-from-employer-perspective": { category: "Compensation", tags: ["salary", "from", "perspective", "employer", "negotiation"] },
  "salary-negotiation-masterclass": { category: "Compensation", tags: ["negotiation", "masterclass", "salary"] },
  "salary-trends-2026-comprehensive": { category: "Compensation", tags: ["2026", "trends", "salary", "comprehensive"] },
  "sales-hiring-playbook": { category: "Industry: Sales", tags: ["sales", "playbook", "hiring"] },
  "sales-leadership-hiring": { category: "Industry: Sales", tags: ["leadership", "sales", "hiring"] },
  "sales-leadership-hiring-playbook": { category: "Industry: Sales", tags: ["leadership", "sales", "playbook", "hiring"] },
  "sales-team-building-guide": { category: "Industry: Sales", tags: ["guide", "sales", "team", "building"] },
  "sdr-bdr-hiring-scaling-guide": { category: "Industry: Sales", tags: ["scaling", "bdr", "hiring", "sdr", "guide"] },
  "sdr-hiring-at-scale": { category: "Industry: Sales", tags: ["scale", "sdr", "hiring"] },
  "sdr-hiring-at-scale-2026": { category: "Industry: Sales", tags: ["scale", "sdr", "2026", "hiring"] },
  "second-chance-hiring-guide": { category: "Diversity & Inclusion", tags: ["guide", "chance", "second", "hiring"] },
  "series-a-gtm-team-building": { category: "Industry: Sales", tags: ["team", "gtm", "series", "building"] },
  "skilled-trades-hiring-crisis": { category: "Industry: Skilled Trades", tags: ["trades", "skilled", "crisis", "hiring"] },
  "skills-based-hiring-implementation": { category: "Skills & Assessment", tags: ["implementation", "skills", "based", "hiring"] },
  "skills-based-hiring-revolution": { category: "Skills & Assessment", tags: ["skills", "based", "revolution", "hiring"] },
  "skills-based-organizations-future": { category: "Skills & Assessment", tags: ["skills", "organizations", "based", "future"] },
  "skills-gap-analysis-guide": { category: "Skills & Assessment", tags: ["skills", "guide", "analysis", "gap"] },
  "skills-taxonomy-building-guide": { category: "Skills & Assessment", tags: ["skills", "taxonomy", "guide", "building"] },
};

export const EXCLUDED_BLOG_SLUGS = {
  "empty_markdown": ["chro-role-evolution-2026", "climate-tech-startup-hiring", "closing-top-sales-talent", "cold-chain-logistics-hiring-guide", "compensation-benchmarking", "competency-based-hiring-framework", "compliance-officer-hiring-guide", "construction-workforce-development", "construction-workforce-strategies", "consulting-firm-hiring-strategies", "consulting-recruitment-strategies", "consulting-talent-pipeline", "content-marketing-team-hiring", "contingent-workforce-management", "contractor-to-fulltime-conversion", "cost-per-hire-reduction-strategies", "counter-offer-strategy", "counteroffer-strategy", "customer-success-team-building", "customs-compliance-careers", "cybersecurity-talent-gap", "cybersecurity-talent-gap-solutions", "cybersecurity-talent-shortage", "cybersecurity-talent-shortage-2026", "data-analytics-team-hiring-guide", "data-driven-recruiting-2025", "data-engineering-hiring-guide", "data-scientist-salary-guide-2026", "defense-industry-hiring-clearances", "dei-hiring-metrics-that-matter", "developer-relations-role-guide", "devops-platform-engineering-hiring", "diversity-hiring-playbook", "diversity-metrics-matter", "diversity-recruiting-strategy-guide", "diversity-sourcing-strategies", "ecommerce-operations-hiring-guide", "ecommerce-team-building", "ecommerce-team-building-guide", "education-technology-hiring", "employee-engagement-strategies", "employee-experience-platform-guide", "employee-referral-program-best-practices", "employee-referral-program-guide", "employer-brand-audit-checklist", "employer-branding-2026", "employer-branding-on-a-budget", "employer-branding-playbook", "employer-branding-roi-framework", "employer-of-record-guide", "employer-value-proposition-guide", "energy-transition-talent-war", "executive-hiring-playbook", "executive-interview-framework", "executive-presence-remote-world", "executive-search-process", "executive-search-vs-subscription-sourcing", "exit-interview-insights-guide", "finance-accounting-salary-guide", "finance-hiring-regulatory-environment", "finance-talent-trends-2026", "fintech-hiring-landscape-2026", "fintech-talent-wars", "fintech-vs-traditional-finance-careers", "four-day-work-week-impact-hiring", "four-day-work-week-implementation", "fractional-executive-hiring-guide", "fractional-executives-guide", "freight-forwarding-digital-transformation", "future-of-contingent-workforce-2026", "future-of-work-2030-predictions", "gaming-industry-talent-acquisition", "gen-z-workforce-expectations", "gen-z-workforce-expectations-2026", "generation-z-hiring", "gig-economy-talent-strategy", "global-supply-chain-talent-shortage", "global-talent-arbitrage-strategy", "global-talent-mobility-2026", "global-trade-routes-talent-strategy", "government-hiring-modernization", "great-resignation-aftermath-2026", "growth-marketing-hiring-guide", "head-of-design-role-guide", "healthcare-hiring-crisis", "healthcare-it-hiring-guide", "healthcare-recruiting-challenges", "healthcare-staffing-crisis-solutions", "high-volume-hiring-strategies", "high-volume-hiring-systems", "hire-full-stack-developer-2026", "hiring-ai-engineers-2026", "hiring-bias-reduction-techniques", "hiring-cfo-board-ready", "hiring-during-recession-playbook", "hiring-for-culture-add-not-culture-fit", "hiring-for-hypergrowth-startups", "hiring-for-startups-vs-enterprise", "hiring-freeze-recovery", "hiring-freeze-talent-strategy", "hiring-manager-kickoff-playbook", "hiring-manager-partnership", "hiring-manager-training-guide", "hospitality-hiring-trends-2026", "hospitality-management-hiring", "hospitality-retention-playbook", "hospitality-retention-strategies", "hospitality-seasonal-hiring-guide", "how-to-write-job-descriptions-that-convert", "hr-people-ops-salary-guide", "hr-team-building-guide-2026", "hr-technology-team-building", "hr-technology-trends-2026", "hybrid-work-model-best-practices", "insurance-hiring-modernization", "insurance-industry-hiring-2026", "insurtech-talent-acquisition", "intermodal-transportation-careers", "internal-mobility-program-guide", "internal-mobility-strategy", "internal-recruiting-vs-outsourcing", "international-hiring-compliance-guide", "interview-feedback-best-practices", "interview-scheduling-nightmare", "interview-scorecards-guide", "job-description-optimization", "labor-market-trends-q1-2026", "legal-hiring-transformation", "legal-hiring-trends-law-firms", "legal-industry-hiring-guide", "legal-tech-talent-acquisition", "logistics-supply-chain-hiring-2026", "logistics-workforce-planning", "longevity-economy-workforce-planning", "management-consulting-recruiting-strategies", "manager-effectiveness-hiring-impact", "manager-hiring-skills-training", "manufacturing-skills-gap-crisis", "marketing-hiring-modern-stack", "marketing-salary-benchmarks-2026", "marketing-talent-2026", "marketing-team-structure-guide", "media-entertainment-hiring-guide", "media-industry-digital-hiring", "mobile-recruiting-strategies", "neurodiversity-hiring-competitive-advantage", "neurodiversity-hiring-guide", "nonprofit-executive-hiring-guide", "nonprofit-hiring-mission-driven-talent", "nonprofit-hiring-strategies", "nurse-recruitment-global-shortage-2026", "nursing-recruitment-best-practices", "offer-letter-best-practices", "offer-negotiation-playbook", "onboarding-90-day-blueprint", "onboarding-best-practices-new-hire-retention", "onboarding-playbook-first-90-days", "onboarding-starts-at-offer", "organizational-design-for-growth", "passive-candidate-sourcing-strategies", "pay-equity-audit-guide", "people-analytics-getting-started", "pharma-biotech-hiring-regulatory-talent", "pharmaceutical-hiring-challenges", "portfolio-career-guide", "predictive-analytics-hiring", "private-equity-portfolio-hiring", "private-equity-portfolio-talent", "private-equity-talent-acquisition", "product-management-hiring-guide", "proptech-talent-acquisition", "public-sector-hiring-modernization", "public-sector-talent-acquisition", "quality-of-hire-measurement-guide", "quiet-quitting-quiet-hiring", "real-estate-hiring-trends", "real-estate-talent-acquisition", "real-estate-talent-acquisition-guide", "recession-proof-recruiting-strategy", "recruiter-burnout-crisis", "recruiter-productivity-tips", "recruiting-in-competitive-markets", "recruiting-metrics-dashboard-guide", "recruitment-analytics-guide", "recruitment-automation-limits", "recruitment-branding-social-media", "recruitment-compliance-guide-2026", "recruitment-funnel-optimization", "recruitment-marketing-content-strategy", "recruitment-process-outsourcing-guide", "recruitment-process-outsourcing-vs-subscription", "recruitment-technology-stack-guide", "reduce-time-to-hire-strategies", "smart-port-automation-hiring", "software-engineer-salary-guide-2026", "solutions-engineer-role-guide", "staffing-agency-internal-hiring", "staffing-agency-recruiter-hiring", "startup-hiring-playbook", "strategic-workforce-planning-guide-2026", "structured-interview-guide-2026", "structured-interview-implementation", "structured-interview-process-guide", "subscription-sourcing-vs-agencies", "succession-planning-framework", "succession-planning-guide", "succession-planning-talent-strategy", "supply-chain-talent-strategy", "sustainable-hiring-practices", "talent-acquisition-strategy-guide-2026", "talent-acquisition-technology-stack", "talent-acquisition-vs-taas", "talent-brand-measurement", "talent-intelligence-competitive-advantage", "talent-market-intelligence-report-q1-2026", "talent-marketplace-internal-mobility", "talent-pipeline-building-guide", "tech-hiring-playbook-startups", "tech-talent-shortage-2026", "technical-interview-design-guide", "total-cost-of-vacancy-analysis", "total-rewards-strategy-beyond-salary", "total-rewards-strategy-guide", "upskilling-reskilling-strategy", "video-interviewing-best-practices", "vr-onboarding-remote-teams", "weekly-candidate-delivery", "workforce-analytics-maturity-model", "workforce-diversity-report-2026", "workforce-planning-guide", "workforce-planning-guide-2026", "workplace-mental-health-strategy"],
  "too_short": [],
  "placeholder_broken": [],
  "test_posts": [],
  "duplicates": [],
} as const;
