import { test } from "@playwright/test";
import { loginAs, seedFixtures, createCvApplication, runPipelineForMatch, pipelineSnapshot, QA_PASSWORD } from "./helpers/qa";
test("dbg record", async ({ page }) => {
  const f = await seedFixtures();
  const stamp = Date.now();
  const pdfLines = ["Debug Person - Client Success Manager", "Seven years B2B SaaS accounts.", "Skills: renewals, QBRs, HubSpot."];
  const content = ["BT","/F1 11 Tf","14 TL","40 760 Td",...pdfLines.map(l=>`(${l}) Tj T*`),"ET"].join("\n");
  const objs = ["<</Type/Catalog/Pages 2 0 R>>","<</Type/Pages/Kids[3 0 R]/Count 1>>","<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]/Resources<</Font<</F1 5 0 R>>>>/Contents 4 0 R>>",`<</Length ${content.length}>>\nstream\n${content}\nendstream`,"<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>"];
  let pdf = "%PDF-1.4\n"; const offs:number[]=[];
  objs.forEach((o,i)=>{offs.push(pdf.length); pdf += `${i+1} 0 obj\n${o}\nendobj\n`;});
  const xref = pdf.length;
  pdf += `xref\n0 ${objs.length+1}\n0000000000 65535 f \n` + offs.map(o=>`${String(o).padStart(10,"0")} 00000 n \n`).join("") + `trailer\n<</Size ${objs.length+1}/Root 1 0 R>>\nstartxref\n${xref}\n%%EOF`;
  const created = await createCvApplication({ positionId: f.position_id, email: `qa+apply-DBG${stamp}@taasflow.test`, fullName: `QA Debug ${stamp}`, cvBase64: Buffer.from(pdf, "latin1").toString("base64"), cvFilename: "dbg.pdf" });
  await runPipelineForMatch(created.candidate_match_id);
  console.log("state", JSON.stringify((await pipelineSnapshot(created.candidate_match_id)).match));
  const bad: string[] = [];
  page.on("response", async (r) => { if (r.status() >= 400 && !r.url().includes("aplo-evnt")) bad.push(`${r.status()} ${r.url()} :: ${(await r.text().catch(()=>"")).slice(0,800)}`); });
  page.on("console", (m) => { if (m.type()==="error" && !m.text().includes("Failed to load resource")) bad.push("console: "+m.text().slice(0,500)); });
  page.on("pageerror", (e) => bad.push("pageerror: "+String(e).slice(0,800)));
  await loginAs(page, "admin", f.users["platform_admin"]!.email, QA_PASSWORD);
  await page.goto(`/admin/candidates/${created.candidate_match_id}`, { waitUntil: "domcontentloaded" });
  await page.waitForTimeout(9000);
  console.log("approve btn count", await page.locator('[data-qa-action="primary-approve-score"]').count());
  console.log("=== SIGNALS\n" + bad.join("\n"));
});
