# Demo candidate definitions. Every field is fictional and marked TAASFLOW_DEMO_SEED.

CANDIDATES = [
    # ---------------- Client Success Manager — EMEA ----------------
    {
        "position": "csm", "stage": "shortlisted", "recommendation": "shortlist",
        "name": "Marta Oliveira", "email": "marta.oliveira@demo.taasflow.com",
        "phone": "+351 912 000 201", "city": "Lisbon", "country": "Portugal",
        "headline": "Client Success Manager — mid-market SaaS, EMEA book",
        "yoe": 6, "notice_weeks": 4, "earliest_start": "2026-09-28",
        "comp": {"target": 50000, "min": 46000, "max": 54000,
                 "note": "Inside the approved range; motivated by the bonus structure."},
        "langs": ["Portuguese (native)", "Spanish (C1)", "English (C2)"],
        "linkedin": "marta-oliveira-demo",
        "skills": ["Account management", "Renewals", "QBRs", "HubSpot", "Zendesk", "Onboarding", "Upsell", "Churn analysis"],
        "current_role": "Senior Client Success Manager",
        "summary": "Six years in mid-market SaaS client success, currently holding a 28-account EMEA book worth EUR 2.1M ARR at 112% net revenue retention. Runs her own onboarding, QBRs and renewals without a manager in the room, and reports in Portuguese, Spanish and English.",
        "cv": {
            "title": "Client Success Manager — mid-market SaaS, EMEA",
            "profile": "Client success manager with 6 years of professional experience owning mid-market B2B SaaS accounts across EMEA. Currently responsible for 28 accounts worth EUR 2.1M ARR at 112% net revenue retention. Runs onboarding, quarterly business reviews and renewals end to end.",
            "skills": "Account management · Renewals · Quarterly business reviews · HubSpot · Zendesk · Onboarding · Expansion · Churn analysis",
            "jobs": [
                ("Senior Client Success Manager — Solvia Software, Lisbon", "2022-03 to present",
                 "Owns a 28-account EMEA portfolio (EUR 2.1M ARR) across Portugal, Spain and the Netherlands. Net revenue retention moved from 98% to 112% in two years. Runs onboarding, monthly health checks, quarterly business reviews and renewal negotiation directly with the client's finance owner. Forecasts renewals in HubSpot with a rolling 90-day view."),
                ("Client Success Manager — Beacon Analytics, Lisbon", "2019-09 to 2022-02",
                 "Managed 40 SMB and lower mid-market accounts. Cut logo churn from 19% to 11% by rebuilding the first-30-day onboarding plan and adding a usage-based health score. Introduced the quarterly business review format still used by the team."),
                ("Account Coordinator — Beacon Analytics, Lisbon", "2018-06 to 2019-08",
                 "Supported the account team on onboarding, renewals administration and Zendesk escalations."),
            ],
            "projects": [
                ("Retention programme", "Designed a usage-based health score in HubSpot and a save-play for accounts flagged red. Applied to 40 accounts; churn on flagged accounts fell by nine points over three quarters."),
                ("Expansion motion", "Built the expansion playbook for seat and module upsell, including the commercial framing used in QBRs. Contributed EUR 310k of expansion ARR in 2025."),
            ],
            "education": "BA Management — ISCTE Lisbon (2015-2018)",
        },
    },
    {
        "position": "csm", "stage": "interview_process", "recommendation": "shortlist",
        "name": "Hugo Antunes", "email": "hugo.antunes@demo.taasflow.com",
        "phone": "+351 912 000 202", "city": "Cascais", "country": "Portugal",
        "headline": "Client Success Manager — HR tech and recruiting platforms",
        "yoe": 5, "notice_weeks": 6, "earliest_start": "2026-10-12",
        "comp": {"target": 48000, "min": 45000, "max": 52000,
                 "note": "Inside range; asked about the retention bonus mechanics."},
        "langs": ["Portuguese (native)", "English (C1)", "Spanish (B2)"],
        "linkedin": "hugo-antunes-demo",
        "skills": ["Client success", "Renewals", "HR tech", "Salesforce", "Onboarding", "Product adoption", "Escalation management"],
        "current_role": "Client Success Manager",
        "summary": "Five years in client success inside HR tech, with direct renewal ownership on a 22-account book worth EUR 1.4M ARR at 104% net revenue retention. Strong domain knowledge of recruiting workflows; Spanish is conversational rather than business fluent.",
        "cv": {
            "title": "Client Success Manager — HR tech",
            "profile": "Client success manager with 5 years of professional experience in HR technology. Owns a 22-account book worth EUR 1.4M ARR with renewal responsibility, at 104% net revenue retention. Deep familiarity with applicant tracking and recruiting workflows.",
            "skills": "Client success · Renewals · Salesforce · Onboarding · Product adoption · Escalation management · ATS workflows",
            "jobs": [
                ("Client Success Manager — Talentis HR, Lisbon", "2021-11 to present",
                 "Owns 22 mid-market HR tech accounts (EUR 1.4M ARR) with full renewal responsibility and 104% net revenue retention. Runs onboarding for new ATS implementations, quarterly business reviews with talent acquisition leaders, and the commercial renewal conversation. Salesforce is the system of record."),
                ("Implementation Consultant — Talentis HR, Lisbon", "2020-01 to 2021-10",
                 "Led 30+ ATS implementations for recruiting teams of 5 to 60 people, including data migration, workflow configuration and administrator training."),
                ("Recruitment Consultant — Ponte Search, Lisbon", "2018-09 to 2019-12",
                 "Agency recruiting for technology roles; managed client relationships and the full candidate process."),
            ],
            "projects": [
                ("Adoption programme", "Built a 90-day adoption plan for new ATS clients tying configuration milestones to usage targets. Time-to-first-hire on the platform dropped from 45 to 28 days."),
                ("Renewal forecast", "Introduced a rolling renewal forecast in Salesforce with risk categories; forecast accuracy inside 5% for four consecutive quarters."),
            ],
            "education": "BA Human Resources Management — Universidade Lusíada (2015-2018)",
        },
    },
    {
        "position": "csm", "stage": "delivered", "recommendation": "review",
        "name": "Rita Salgado", "email": "rita.salgado@demo.taasflow.com",
        "phone": "+351 912 000 203", "city": "Porto", "country": "Portugal",
        "headline": "Customer Success Manager — SMB portfolio, moving to mid-market",
        "yoe": 4, "notice_weeks": 4, "earliest_start": "2026-09-28",
        "comp": {"target": 44000, "min": 41000, "max": 47000,
                 "note": "Inside range at the lower end; relocation to Lisbon needs discussion."},
        "langs": ["Portuguese (native)", "English (C1)"],
        "linkedin": "rita-salgado-demo",
        "skills": ["Customer success", "Onboarding", "Zendesk", "HubSpot", "Health scoring", "Training"],
        "current_role": "Customer Success Manager",
        "summary": "Four years in SMB customer success with recent renewal exposure on a 60-account book. Owns onboarding and health scoring end to end, but has not yet run commercial renewals above EUR 30k, and is based in Porto with relocation still open.",
        "cv": {
            "title": "Customer Success Manager — SMB SaaS",
            "profile": "Customer success manager with 4 years of professional experience in B2B SaaS. Owns a 60-account SMB book with onboarding, adoption and, since 2025, renewal responsibility. Comfortable with health scoring and training at volume.",
            "skills": "Customer success · Onboarding · Zendesk · HubSpot · Health scoring · Customer training · Escalations",
            "jobs": [
                ("Customer Success Manager — Vento Cloud, Porto", "2022-04 to present",
                 "Owns 60 SMB accounts (average EUR 14k ARR). Took on renewal responsibility in early 2025; renewal rate 91% since. Runs group onboarding sessions and a monthly usage review, and manages escalations through Zendesk."),
                ("Customer Support Lead — Vento Cloud, Porto", "2020-06 to 2022-03",
                 "Led a three-person support team, set the first response and resolution targets, and built the internal knowledge base."),
                ("Support Specialist — Vento Cloud, Porto", "2019-02 to 2020-05",
                 "Front-line support for a SaaS product, mostly written, in Portuguese and English."),
            ],
            "projects": [
                ("Onboarding at volume", "Replaced one-to-one onboarding with a cohort model plus a self-serve checklist. Onboarding capacity tripled without adding headcount and activation stayed flat."),
                ("Health score v1", "Built the first account health score from product usage and support volume; now used to trigger the save-play across the SMB book."),
            ],
            "education": "BA Communication Sciences — Universidade do Porto (2016-2019)",
        },
    },
    {
        "position": "csm", "stage": "not_moving_forward", "recommendation": "do_not_recommend",
        "name": "Nuno Vasques", "email": "nuno.vasques@demo.taasflow.com",
        "phone": "+351 912 000 204", "city": "Lisbon", "country": "Portugal",
        "headline": "Technical Support Manager — B2B SaaS",
        "yoe": 7, "notice_weeks": 8, "earliest_start": "2026-11-02",
        "comp": {"target": 47000, "min": 44000, "max": 50000,
                 "note": "Inside range, but the role he wants is support leadership rather than commercial ownership."},
        "langs": ["Portuguese (native)", "English (C1)"],
        "linkedin": "nuno-vasques-demo",
        "skills": ["Technical support", "Team leadership", "Zendesk", "SLA management", "Incident management"],
        "current_role": "Technical Support Manager",
        "summary": "Seven years in technical support, five of them leading a team of eight. Strong on service levels and incident handling, but has never owned renewals, expansion or a revenue number, which is the core of this role.",
        "cv": {
            "title": "Technical Support Manager",
            "profile": "Support leader with 7 years of professional experience in B2B SaaS, currently managing an eight-person technical support team. Owns service levels, escalation paths and the support tooling stack. No commercial or renewal ownership to date.",
            "skills": "Technical support · Team leadership · Zendesk administration · SLA management · Incident management · Knowledge base",
            "jobs": [
                ("Technical Support Manager — Aurora Systems, Lisbon", "2021-01 to present",
                 "Manages eight support engineers across two tiers. Owns first-response and resolution service levels (95% inside target), the escalation path to engineering, and Zendesk administration. Reports support volume and CSAT to the leadership team monthly."),
                ("Senior Support Engineer — Aurora Systems, Lisbon", "2018-05 to 2020-12",
                 "Tier-two support for an infrastructure product; wrote the incident runbooks still in use."),
                ("Support Engineer — Delta IT, Lisbon", "2016-09 to 2018-04",
                 "Front-line technical support for enterprise clients."),
            ],
            "projects": [
                ("Support restructure", "Split a single queue into two tiers with clear ownership; median resolution time fell from 19 to 7 hours."),
                ("Knowledge base", "Wrote and maintained 140 articles; deflected roughly 20% of inbound tickets."),
            ],
            "education": "BSc Computer Engineering — Instituto Superior Técnico (2012-2016)",
        },
    },

    # ---------------- Revenue Operations Analyst ----------------
    {
        "position": "revops", "stage": "shortlisted", "recommendation": "shortlist",
        "name": "Filipa Andrade", "email": "filipa.andrade@demo.taasflow.com",
        "phone": "+351 912 000 205", "city": "Lisbon", "country": "Portugal",
        "headline": "Revenue Operations Analyst — SQL, dbt, Looker",
        "yoe": 5, "notice_weeks": 4, "earliest_start": "2026-10-19",
        "comp": {"target": 45000, "min": 42000, "max": 48000,
                 "note": "Inside the approved range."},
        "langs": ["Portuguese (native)", "English (C2)"],
        "linkedin": "filipa-andrade-demo",
        "skills": ["SQL", "dbt", "Looker", "Snowflake", "Forecasting", "Salesforce", "Python", "SaaS metrics"],
        "current_role": "Revenue Operations Analyst",
        "summary": "Five years in revenue operations, owning pipeline and forecast reporting for a fourteen-person commercial team. Writes production SQL against Snowflake, maintains a dbt layer, and publishes the metric definitions the company forecasts against.",
        "cv": {
            "title": "Revenue Operations Analyst — SQL, dbt, Looker",
            "profile": "Revenue operations analyst with 5 years of professional experience. Owns pipeline, forecast and retention reporting for a 14-person commercial team. Advanced SQL against Snowflake, a maintained dbt transformation layer, and Looker dashboards used in the weekly pipeline review.",
            "skills": "SQL · dbt · Looker · Snowflake · Salesforce · Python · Forecasting · SaaS metrics (ARR, NRR, CAC)",
            "jobs": [
                ("Revenue Operations Analyst — Northline SaaS, Lisbon", "2022-06 to present",
                 "Owns the reporting layer for a 14-person commercial team: pipeline, forecast, retention and cohort analysis. Rebuilt weekly pipeline review off Snowflake with a dbt model instead of CRM exports, cutting preparation from six hours to twenty minutes. Wrote the company metric dictionary defining ARR, NRR, win rate and pipeline coverage."),
                ("Sales Operations Analyst — Northline SaaS, Lisbon", "2021-01 to 2022-05",
                 "Maintained Salesforce data hygiene, territory assignment and quota tracking. Built the first deduplication process for accounts and contacts, removing 3,400 duplicate records."),
                ("Business Analyst — Cardoso Consulting, Lisbon", "2019-09 to 2020-12",
                 "SQL and Excel analysis for retail and logistics clients, including demand reporting and margin analysis."),
            ],
            "projects": [
                ("Forecast model", "Built a bottom-up forecast in dbt combining stage-weighted pipeline and historical conversion by segment. Forecast error under 6% for five consecutive quarters."),
                ("Self-serve reporting", "Converted the twelve most requested ad-hoc reports into documented Looker explores; recurring analyst requests fell by roughly 70%."),
            ],
            "education": "MSc Economics — Nova SBE (2017-2019)",
        },
    },
    {
        "position": "revops", "stage": "interview_process", "recommendation": "shortlist",
        "name": "Joana Rocha", "email": "joana.rocha@demo.taasflow.com",
        "phone": "+351 912 000 206", "city": "Braga", "country": "Portugal",
        "headline": "Business Analyst — SQL and Python, moving into RevOps",
        "yoe": 4, "notice_weeks": 2, "earliest_start": "2026-09-21",
        "comp": {"target": 43000, "min": 40000, "max": 46000,
                 "note": "Inside range."},
        "langs": ["Portuguese (native)", "English (C1)", "French (B1)"],
        "linkedin": "joana-rocha-demo",
        "skills": ["SQL", "Python", "Metabase", "BigQuery", "Cohort analysis", "Reporting automation"],
        "current_role": "Business Analyst",
        "summary": "Four years of analytics with strong SQL and Python against BigQuery, and Metabase dashboards used across the business. Pipeline and forecast reporting is adjacent rather than owned: her reporting has been product and marketing led.",
        "cv": {
            "title": "Business Analyst — SQL, Python, BigQuery",
            "profile": "Analyst with 4 years of professional experience covering product, marketing and commercial reporting. Advanced SQL against BigQuery, Python for analysis and automation, and Metabase dashboards used daily by three teams.",
            "skills": "SQL · Python · BigQuery · Metabase · Cohort analysis · Reporting automation · A/B testing",
            "jobs": [
                ("Business Analyst — Setal Digital, Braga", "2023-02 to present",
                 "Owns the analytics layer for product and marketing: acquisition funnels, cohort retention, and a weekly commercial summary shared with the sales lead. Automated eleven recurring reports in Python, replacing manual spreadsheet work."),
                ("Data Analyst — Setal Digital, Braga", "2021-08 to 2023-01",
                 "Built the first BigQuery reporting models and the Metabase instance now used company-wide."),
                ("Junior Analyst — Braga Retail Group", "2020-09 to 2021-07",
                 "Sales and stock reporting in SQL and Excel for a 40-store retail chain."),
            ],
            "projects": [
                ("Cohort retention model", "Built a monthly cohort retention model in SQL that became the standard view for the product and commercial teams."),
                ("Reporting automation", "Replaced eleven manual reports with a scheduled Python pipeline; roughly one day per week of analyst time recovered."),
            ],
            "education": "BSc Applied Mathematics — Universidade do Minho (2017-2020)",
        },
    },
    {
        "position": "revops", "stage": "delivered", "recommendation": "review",
        "name": "André Pinto", "email": "andre.pinto@demo.taasflow.com",
        "phone": "+351 912 000 207", "city": "Lisbon", "country": "Portugal",
        "headline": "Sales Operations Analyst — Salesforce and Power BI",
        "yoe": 3, "notice_weeks": 4, "earliest_start": "2026-10-19",
        "comp": {"target": 42000, "min": 39000, "max": 45000,
                 "note": "Inside range."},
        "langs": ["Portuguese (native)", "English (B2)"],
        "linkedin": "andre-pinto-demo",
        "skills": ["Salesforce", "Power BI", "SQL", "Quota planning", "CRM hygiene"],
        "current_role": "Sales Operations Analyst",
        "summary": "Three years in sales operations with real pipeline and quota reporting ownership in Salesforce and Power BI. SQL is intermediate and reporting sits mostly on CRM exports rather than a warehouse, which is the gap for this role.",
        "cv": {
            "title": "Sales Operations Analyst — Salesforce, Power BI",
            "profile": "Sales operations analyst with 3 years of professional experience supporting a ten-person sales team. Owns pipeline and quota reporting in Salesforce and Power BI, plus CRM data hygiene. Intermediate SQL, mostly against a replica database.",
            "skills": "Salesforce administration · Power BI · SQL (intermediate) · Quota planning · CRM data hygiene · Excel modelling",
            "jobs": [
                ("Sales Operations Analyst — Vela Industrial, Lisbon", "2023-05 to present",
                 "Owns the weekly pipeline report and monthly quota attainment for ten sales representatives. Maintains Salesforce fields, validation rules and dashboards. Runs a quarterly CRM cleanup and the territory assignment file."),
                ("Sales Support Analyst — Vela Industrial, Lisbon", "2022-01 to 2023-04",
                 "Quote preparation, order tracking and Excel-based commission calculations."),
                ("Commercial Intern — Vela Industrial, Lisbon", "2021-06 to 2021-12",
                 "Supported the commercial team with reporting and data entry."),
            ],
            "projects": [
                ("Pipeline dashboard", "Replaced a weekly spreadsheet with a Power BI pipeline dashboard fed from Salesforce; the sales review now runs from a single source."),
                ("Commission model", "Rebuilt the commission calculation in a controlled Excel model with an audit trail, ending recurring disputes."),
            ],
            "education": "BA Management — ISEG Lisbon (2018-2021)",
        },
    },
    {
        "position": "revops", "stage": "not_moving_forward", "recommendation": "do_not_recommend",
        "name": "Bruno Teles", "email": "bruno.teles@demo.taasflow.com",
        "phone": "+351 912 000 208", "city": "Setúbal", "country": "Portugal",
        "headline": "Financial Controller — reporting and budgeting",
        "yoe": 8, "notice_weeks": 8, "earliest_start": "2026-11-16",
        "comp": {"target": 52000, "min": 50000, "max": 58000,
                 "note": "Above the approved range for this role."},
        "langs": ["Portuguese (native)", "English (B2)"],
        "linkedin": "bruno-teles-demo",
        "skills": ["Financial controlling", "Budgeting", "Excel modelling", "SAP", "Month-end close"],
        "current_role": "Financial Controller",
        "summary": "Eight years in financial control with strong budgeting and month-end discipline, but the reporting stack is Excel and SAP rather than SQL and a warehouse, and there is no pipeline or forecast ownership for a commercial team.",
        "cv": {
            "title": "Financial Controller",
            "profile": "Financial controller with 8 years of professional experience in industrial and retail businesses. Owns budgeting, month-end close and management reporting. Reporting is built in Excel on SAP extracts; no warehouse or SQL work to date.",
            "skills": "Financial controlling · Budgeting and forecasting · Excel modelling · SAP · Month-end close · Variance analysis",
            "jobs": [
                ("Financial Controller — Sado Industrial, Setúbal", "2020-03 to present",
                 "Owns the annual budget (EUR 24M turnover), monthly close and the management reporting pack. Runs variance analysis with department heads and prepares the board reporting file."),
                ("Assistant Controller — Sado Industrial, Setúbal", "2017-09 to 2020-02",
                 "Supported close, cost accounting and inventory valuation."),
                ("Audit Associate — Marques & Associados, Lisbon", "2015-09 to 2017-08",
                 "Statutory audit for mid-sized Portuguese companies."),
            ],
            "projects": [
                ("Budget rebuild", "Rebuilt the annual budget model by cost centre with a documented assumption sheet; the close cycle shortened by three days."),
                ("Cost reporting", "Introduced a monthly cost-per-unit report used by operations to price contracts."),
            ],
            "education": "MSc Finance — ISCTE Business School (2013-2015)",
        },
    },

    # ---------------- Head of Operations (filled) ----------------
    {
        "position": "ops", "stage": "hired", "recommendation": "shortlist",
        "name": "Cláudia Ferreira", "email": "claudia.ferreira@demo.taasflow.com",
        "phone": "+351 912 000 209", "city": "Lisbon", "country": "Portugal",
        "headline": "Head of Operations — staffing and delivery, multi-site",
        "yoe": 12, "notice_weeks": 8, "earliest_start": "2026-09-01",
        "comp": {"target": 82000, "min": 78000, "max": 86000,
                 "note": "Agreed at EUR 82,000 base plus the 20% operating bonus."},
        "langs": ["Portuguese (native)", "English (C2)", "Spanish (C1)"],
        "linkedin": "claudia-ferreira-demo",
        "skills": ["Operations leadership", "P&L ownership", "Process design", "Vendor management", "Capacity planning", "ATS implementation", "Multi-site management"],
        "current_role": "Operations Director",
        "summary": "Twelve years in staffing and delivery operations, currently running a EUR 3.4M budget and four team leads across two countries. Has led an ATS implementation end to end and opened one new market, which maps directly to the mandate for this role.",
        "cv": {
            "title": "Operations Director — staffing and delivery",
            "profile": "Operations leader with 12 years of professional experience in staffing and professional services. Currently Operations Director for a EUR 3.4M departmental budget with four team leads across Portugal and Spain. Owns delivery operations, vendor contracts, systems and operating reporting.",
            "skills": "Operations leadership · P&L and budget ownership · Process design · Vendor management · Capacity planning · ATS implementation · Multi-site management",
            "jobs": [
                ("Operations Director — Arco Staffing, Lisbon", "2020-02 to present",
                 "Owns delivery operations across Lisbon, Porto and Madrid with a EUR 3.4M budget and four team leads. Published the operating model for delivery, introduced a monthly operating review with service-level and margin reporting, and renegotiated the two largest vendor contracts for a 14% annual saving. Opened the Madrid office including hiring, systems and local process."),
                ("Head of Delivery Operations — Arco Staffing, Lisbon", "2017-06 to 2020-01",
                 "Managed two team leads and 18 delivery staff. Led the ATS implementation end to end: vendor selection, data migration for 40,000 records, workflow design and training."),
                ("Operations Manager — Talento Group, Porto", "2014-03 to 2017-05",
                 "Ran the Porto delivery team, owned the service-level framework and the client reporting pack."),
            ],
            "projects": [
                ("Operating model", "Documented process ownership across delivery, sourcing and administration, with named owners and service levels. Client escalations fell by a third in the first year."),
                ("Systems consolidation", "Replaced three overlapping tools with a single ATS and reporting layer; annual licence cost down EUR 120k with no loss of coverage."),
            ],
            "education": "MBA — Católica Lisbon School of Business (2012-2014); BA Management — Universidade do Porto (2006-2009)",
        },
    },
    {
        "position": "ops", "stage": "not_moving_forward", "recommendation": "review",
        "name": "Vasco Lima", "email": "vasco.lima@demo.taasflow.com",
        "phone": "+351 912 000 210", "city": "Porto", "country": "Portugal",
        "headline": "Operations Manager — logistics and shared services",
        "yoe": 9, "notice_weeks": 8, "earliest_start": "2026-10-01",
        "comp": {"target": 76000, "min": 72000, "max": 80000,
                 "note": "Inside range."},
        "langs": ["Portuguese (native)", "English (C1)"],
        "linkedin": "vasco-lima-demo",
        "skills": ["Operations management", "Process improvement", "Budget ownership", "Vendor management", "Lean"],
        "current_role": "Operations Manager",
        "summary": "Nine years in operations with a EUR 1.8M budget and two supervisors reporting to him, strong on process improvement and vendor work. The gap is domain: his experience is logistics and shared services rather than staffing or recruiting delivery.",
        "cv": {
            "title": "Operations Manager — logistics and shared services",
            "profile": "Operations manager with 9 years of professional experience in logistics and shared services. Owns a EUR 1.8M operating budget and manages two supervisors and 26 staff. Lean practitioner with a record of measured process improvement.",
            "skills": "Operations management · Process improvement · Lean · Budget ownership · Vendor management · Warehouse systems",
            "jobs": [
                ("Operations Manager — Douro Logistics, Porto", "2019-04 to present",
                 "Owns a EUR 1.8M operating budget across two sites, managing two supervisors and 26 staff. Redesigned the inbound process to cut handling cost per unit by 18%. Manages five vendor contracts and the annual tender cycle."),
                ("Shared Services Team Lead — Douro Logistics, Porto", "2016-09 to 2019-03",
                 "Led the shared services team covering invoicing, scheduling and administration."),
                ("Process Analyst — Norte Manufacturing, Braga", "2014-06 to 2016-08",
                 "Time and motion analysis, standard operating procedure documentation and Lean projects."),
            ],
            "projects": [
                ("Inbound redesign", "Mapped and rebuilt the inbound flow across two sites; handling cost per unit down 18% and dock waiting time halved."),
                ("Tender cycle", "Standardised the vendor tender process with a scoring model; three of five contracts renegotiated at better terms."),
            ],
            "education": "BSc Industrial Engineering — Universidade do Minho (2010-2014)",
        },
    },
    {
        "position": "ops", "stage": "not_moving_forward", "recommendation": "do_not_recommend",
        "name": "Sara Melo", "email": "sara.melo@demo.taasflow.com",
        "phone": "+351 912 000 211", "city": "Lisbon", "country": "Portugal",
        "headline": "Senior Project Manager — professional services",
        "yoe": 7, "notice_weeks": 4, "earliest_start": "2026-09-15",
        "comp": {"target": 68000, "min": 64000, "max": 72000,
                 "note": "Below the approved range."},
        "langs": ["Portuguese (native)", "English (C1)"],
        "linkedin": "sara-melo-demo",
        "skills": ["Project management", "Stakeholder management", "PMO", "Reporting", "Change management"],
        "current_role": "Senior Project Manager",
        "summary": "Seven years of project delivery with strong stakeholder and reporting discipline, but no line management of managers and no budget ownership, which are both explicit requirements for this leadership role.",
        "cv": {
            "title": "Senior Project Manager — professional services",
            "profile": "Project manager with 7 years of professional experience delivering client-facing programmes in professional services. Runs multi-workstream projects with senior stakeholders. Individual contributor with no direct reports and no budget ownership.",
            "skills": "Project management · Stakeholder management · PMO reporting · Change management · Risk management",
            "jobs": [
                ("Senior Project Manager — Meridian Consulting, Lisbon", "2021-02 to present",
                 "Delivers client transformation programmes of up to nine months across three workstreams. Owns plan, risk log and steering committee reporting. Coordinates 12 to 20 people per programme without line authority."),
                ("Project Manager — Meridian Consulting, Lisbon", "2019-01 to 2021-01",
                 "Ran mid-size client projects and the internal PMO reporting cycle."),
                ("Business Analyst — Meridian Consulting, Lisbon", "2017-09 to 2018-12",
                 "Requirements gathering and process mapping for client engagements."),
            ],
            "projects": [
                ("Programme turnaround", "Took over a delayed client programme, reset the plan and scope with the steering committee, and delivered the remaining phases on the revised date."),
                ("PMO reporting", "Standardised status reporting across eleven concurrent projects into a single weekly pack."),
            ],
            "education": "BA Business Administration — Universidade Nova de Lisboa (2013-2016)",
        },
    },
]
