/**
 * TaaSFlow Public Navigation — Single Source of Truth
 * ---------------------------------------------------
 * Every rendered public header/footer link on the destination MUST come
 * from this file. Placeholders / not-yet-migrated routes are marked with
 * `hidden: true` and are NOT rendered — never publish broken links.
 *
 * See docs/design/public-navigation-map.json for a JSON-serialisable
 * snapshot; that file is generated by importing this module.
 */

export type NavLink = {
  to: string;
  label: string;
  description?: string;
  hidden?: boolean;
  external?: boolean;
};

export type NavGroup = {
  label: string;
  links: NavLink[];
};

/* -------------------------------------------------------------- CTAs */

export const PRIMARY_CTA: NavLink = {
  to: "/intake",
  label: "Start hiring",
  description: "Launch a role — canonical employer intake",
};

export const SECONDARY_CTAS: NavLink[] = [
  { to: "/jobs",  label: "Browse jobs" },
  { to: "/login", label: "Sign in" },
];

/* -------------------------------------------------------------- Primary nav (grouped) */

export const NAV_GROUPS: NavGroup[] = [
  {
    label: "Solutions",
    links: [
      { to: "/solutions",              label: "TaaSFlow for employers", description: "Live, ranked candidate delivery" },
      { to: "/how-it-works",           label: "How it works",           description: "Intake → screening → scoring → shortlist" },
      { to: "/enterprise",             label: "Enterprise",             description: "Compliance, security, and scale" },
      { to: "/partnerships/staffing",  label: "Staffing partnerships",  description: "White-label and referral programs" },
      { to: "/pricing",                label: "Pricing",                description: "Plans and pilots" },
    ],
  },
  {
    label: "Industries",
    links: [
      { to: "/industries",              label: "Industries overview" },
      { to: "/industries/technology",   label: "Technology" },
      { to: "/industries/financial-services", label: "Financial services" },
      { to: "/industries/legal",        label: "Legal" },
      { to: "/industries/healthcare",   label: "Healthcare" },
      { to: "/industries/sales-marketing", label: "Sales & marketing" },
    ],
  },
  {
    label: "Resources",
    links: [
      { to: "/resources",       label: "Resources hub" },
      { to: "/blog",            label: "Blog" },
      { to: "/case-studies",    label: "Case studies" },
      { to: "/knowledge-base",  label: "Knowledge base" },
      { to: "/faq",             label: "FAQ" },
    ],
  },
  {
    label: "About",
    links: [
      { to: "/about",   label: "About TaaSFlow" },
      { to: "/journey", label: "TaaSFlow journey" },
      { to: "/contact", label: "Contact" },
    ],
  },
];

/** Flat primary nav shown on desktop (top-level entries). */
export const PRIMARY_NAV: NavLink[] = [
  { to: "/jobs", label: "Jobs" },
];

/* -------------------------------------------------------------- Footer groups */

export const FOOTER_GROUPS: NavGroup[] = [
  {
    label: "Company",
    links: [
      { to: "/about",   label: "About" },
      { to: "/journey", label: "Journey" },
      { to: "/contact", label: "Contact" },
    ],
  },
  {
    label: "Solutions",
    links: [
      { to: "/solutions",             label: "Solutions" },
      { to: "/how-it-works",          label: "How it works" },
      { to: "/enterprise",            label: "Enterprise" },
      { to: "/employer-onboarding",   label: "Employer onboarding" },
      { to: "/partnerships/staffing", label: "Staffing partnership" },
    ],
  },
  {
    label: "Employers",
    links: [
      { to: "/intake",     label: "Start hiring" },
      { to: "/pilot",      label: "Pilot" },
      { to: "/pricing",    label: "Pricing" },
      { to: "/industries", label: "Industries" },
      { to: "/login",      label: "Client sign in" },
    ],
  },
  {
    label: "Candidates",
    links: [
      { to: "/jobs",              label: "Browse jobs" },
      { to: "/talent-network",    label: "Talent network" },
      { to: "/candidate-success", label: "Candidate success" },
      { to: "/journey",           label: "Candidate journey" },
      { to: "/login",             label: "Candidate sign in" },
    ],
  },
  {
    label: "Resources",
    links: [
      { to: "/resources",      label: "Resources" },
      { to: "/blog",           label: "Blog" },
      { to: "/case-studies",   label: "Case studies" },
      { to: "/knowledge-base", label: "Knowledge base" },
      { to: "/faq",            label: "FAQ" },
    ],
  },
  {
    label: "Legal",
    links: [
      { to: "/privacy", label: "Privacy" },
      { to: "/terms",   label: "Terms" },
      { to: "/sitemap.xml", label: "Sitemap", external: true },
    ],
  },
];

export const SOCIAL_LINKS = [
  { href: "https://www.linkedin.com/company/taasflow", label: "LinkedIn" },
  { href: "mailto:hello@taasflow.com",                 label: "Email" },
] as const;

/** Utility: filter hidden links and produce a flat list for QA / crawling. */
export function allNavHrefs(): string[] {
  const out = new Set<string>();
  const push = (l: NavLink) => { if (!l.hidden) out.add(l.to); };
  PRIMARY_NAV.forEach(push);
  NAV_GROUPS.forEach((g) => g.links.forEach(push));
  FOOTER_GROUPS.forEach((g) => g.links.forEach(push));
  push(PRIMARY_CTA);
  SECONDARY_CTAS.forEach(push);
  return Array.from(out);
}
