/**
 * "What employers see" — candidate-side read of the employer DTO.
 *
 * The preview is generated by the same builder (`toClientCandidateDTO`) and the
 * same column selection (`CLIENT_CANDIDATE_SELECT`) that produce the employer's
 * candidate page, so the two shapes cannot drift.
 */
import { createServerFn } from "@tanstack/react-start";
import { cvConsentGate } from "@/lib/consent/cv-consent-gate";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { z } from "zod";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyRow = any;

async function myProfileIds(supabase: AnyRow, userId: string): Promise<string[]> {
  const { data } = await supabase
    .from("candidate_profiles")
    .select("id")
    .eq("auth_user_id", userId);
  return ((data as AnyRow[]) ?? []).map((r) => String(r.id));
}

/** Applications of mine that have actually been shared with an employer. */
export const listMyEmployerPreviews = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const supabase = context.supabase as AnyRow;
    const cpIds = await myProfileIds(supabase, context.userId);
    if (cpIds.length === 0) return { shared: [] as AnyRow[] };

    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data, error } = await supabaseAdmin
      .from("candidate_matches")
      .select(
        `id, stage, delivered_at, contact_released_at, contact_released_by, contact_release_reason,
         positions:position_id ( title, organizations:organization_id ( name ) )`,
      )
      .in("candidate_profile_id", cpIds)
      .eq("client_visibility", "visible")
      .order("delivered_at", { ascending: false })
      .limit(50);
    if (error) throw new Error(error.message);

    return {
      shared: ((data as AnyRow[]) ?? []).map((m) => ({
        match_id: String(m.id),
        role_title: (m.positions?.title as string | undefined) ?? "Role",
        company: (m.positions?.organizations?.name as string | undefined) ?? null,
        shared_at: (m.delivered_at as string | null) ?? null,
        contact_released: cvConsentGate({
          stage: m.stage as string,
          contact_released_at: m.contact_released_at as string | null,
          contact_released_by: m.contact_released_by as string | null,
          contact_release_reason: m.contact_release_reason as string | null,
        }).open,
      })),
    };
  });

/** The exact employer DTO for one of my own shared applications. */
export const getMyEmployerPreview = createServerFn({ method: "GET" })
  .middleware([requireSupabaseAuth])
  .inputValidator((input: { match_id: string }) =>
    z.object({ match_id: z.string().uuid() }).parse(input),
  )
  .handler(async ({ context, data }) => {
    const supabase = context.supabase as AnyRow;
    const cpIds = await myProfileIds(supabase, context.userId);
    if (cpIds.length === 0) throw new Error("profile_not_found");

    const { toClientCandidateDTO, CLIENT_CANDIDATE_SELECT, loadClientEvidenceItems } =
      await import("@/lib/client-kpi.server");
    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

    const { data: match, error } = await supabaseAdmin
      .from("candidate_matches")
      .select(`${CLIENT_CANDIDATE_SELECT}, organization_id, updated_at`)
      .eq("id", data.match_id)
      .eq("client_visibility", "visible")
      .in("candidate_profile_id", cpIds)
      .maybeSingle();
    if (error) throw new Error(error.message);
    if (!match) throw new Error("not_shared");

    const row = match as AnyRow;
    const [answersRes, auditRes, evidenceByMatch] = await Promise.all([
      row.application_id
        ? supabaseAdmin
            .from("application_answers")
            .select("id, answer, screening_questions(question, display_order)")
            .eq("application_id", row.application_id)
        : Promise.resolve({ data: [] as AnyRow[] }),
      supabaseAdmin
        .from("audit_events")
        .select("id, action, entity_type, actor_user_id, before_state, after_state, created_at")
        .eq("organization_id", row.organization_id)
        .eq("entity_id", data.match_id)
        .order("created_at", { ascending: false })
        .limit(30),
      loadClientEvidenceItems(supabaseAdmin as AnyRow, [data.match_id]),
    ]);

    const answers = (((answersRes as AnyRow).data as AnyRow[]) ?? []).slice().sort(
      (a, b) =>
        (a.screening_questions?.display_order ?? 0) - (b.screening_questions?.display_order ?? 0),
    );

    const dto = toClientCandidateDTO({
      ...row,
      evidence_items: evidenceByMatch.get(data.match_id) ?? [],
      application_answers: answers,
      audit_events: ((auditRes as AnyRow).data as AnyRow[]) ?? [],
    });

    return {
      dto,
      contact_released: dto.contact_released,
    };

  });
