/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as IntakeConfirmationRouteImport } from './routes/intake.confirmation'
import { Route as JobsIdApplyRouteImport } from './routes/jobs.$id.apply'
import { Route as ApplyReceivedApplicationIdRouteImport } from './routes/apply.received.$applicationId'
import { Route as AuthenticatedAdminMatchesRouteImport } from './routes/_authenticated/admin.matches'
import { Route as AuthenticatedAdminMatchesIdRouteImport } from './routes/_authenticated/admin.matches.$id'

const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const IntakeConfirmationRoute = IntakeConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => IntakeRoute,
} as any)
const JobsIdApplyRoute = JobsIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsIdRoute,
} as any)
const ApplyReceivedApplicationIdRoute =
  ApplyReceivedApplicationIdRouteImport.update({
    id: '/apply/received/$applicationId',
    path: '/apply/received/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminMatchesRoute =
  AuthenticatedAdminMatchesRouteImport.update({
    id: '/admin/matches',
    path: '/admin/matches',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMatchesIdRoute =
  AuthenticatedAdminMatchesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminMatchesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/intake': typeof IntakeRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/intake/confirmation': typeof IntakeConfirmationRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/admin/matches': typeof AuthenticatedAdminMatchesRouteWithChildren
  '/apply/received/$applicationId': typeof ApplyReceivedApplicationIdRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/admin/matches/$id': typeof AuthenticatedAdminMatchesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/intake': typeof IntakeRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/intake/confirmation': typeof IntakeConfirmationRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/admin/matches': typeof AuthenticatedAdminMatchesRouteWithChildren
  '/apply/received/$applicationId': typeof ApplyReceivedApplicationIdRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/admin/matches/$id': typeof AuthenticatedAdminMatchesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/intake': typeof IntakeRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/intake/confirmation': typeof IntakeConfirmationRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/_authenticated/admin/matches': typeof AuthenticatedAdminMatchesRouteWithChildren
  '/apply/received/$applicationId': typeof ApplyReceivedApplicationIdRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/_authenticated/admin/matches/$id': typeof AuthenticatedAdminMatchesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/intake'
    | '/jobs'
    | '/intake/confirmation'
    | '/jobs/$id'
    | '/admin/matches'
    | '/apply/received/$applicationId'
    | '/jobs/$id/apply'
    | '/admin/matches/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/intake'
    | '/jobs'
    | '/intake/confirmation'
    | '/jobs/$id'
    | '/admin/matches'
    | '/apply/received/$applicationId'
    | '/jobs/$id/apply'
    | '/admin/matches/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/intake'
    | '/jobs'
    | '/intake/confirmation'
    | '/jobs/$id'
    | '/_authenticated/admin/matches'
    | '/apply/received/$applicationId'
    | '/jobs/$id/apply'
    | '/_authenticated/admin/matches/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IntakeRoute: typeof IntakeRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  ApplyReceivedApplicationIdRoute: typeof ApplyReceivedApplicationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/intake/confirmation': {
      id: '/intake/confirmation'
      path: '/confirmation'
      fullPath: '/intake/confirmation'
      preLoaderRoute: typeof IntakeConfirmationRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/jobs/$id/apply': {
      id: '/jobs/$id/apply'
      path: '/apply'
      fullPath: '/jobs/$id/apply'
      preLoaderRoute: typeof JobsIdApplyRouteImport
      parentRoute: typeof JobsIdRoute
    }
    '/apply/received/$applicationId': {
      id: '/apply/received/$applicationId'
      path: '/apply/received/$applicationId'
      fullPath: '/apply/received/$applicationId'
      preLoaderRoute: typeof ApplyReceivedApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/matches': {
      id: '/_authenticated/admin/matches'
      path: '/admin/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AuthenticatedAdminMatchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/matches/$id': {
      id: '/_authenticated/admin/matches/$id'
      path: '/$id'
      fullPath: '/admin/matches/$id'
      preLoaderRoute: typeof AuthenticatedAdminMatchesIdRouteImport
      parentRoute: typeof AuthenticatedAdminMatchesRoute
    }
  }
}

interface AuthenticatedAdminMatchesRouteChildren {
  AuthenticatedAdminMatchesIdRoute: typeof AuthenticatedAdminMatchesIdRoute
}

const AuthenticatedAdminMatchesRouteChildren: AuthenticatedAdminMatchesRouteChildren =
  {
    AuthenticatedAdminMatchesIdRoute: AuthenticatedAdminMatchesIdRoute,
  }

const AuthenticatedAdminMatchesRouteWithChildren =
  AuthenticatedAdminMatchesRoute._addFileChildren(
    AuthenticatedAdminMatchesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminMatchesRoute: typeof AuthenticatedAdminMatchesRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminMatchesRoute: AuthenticatedAdminMatchesRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface IntakeRouteChildren {
  IntakeConfirmationRoute: typeof IntakeConfirmationRoute
}

const IntakeRouteChildren: IntakeRouteChildren = {
  IntakeConfirmationRoute: IntakeConfirmationRoute,
}

const IntakeRouteWithChildren =
  IntakeRoute._addFileChildren(IntakeRouteChildren)

interface JobsIdRouteChildren {
  JobsIdApplyRoute: typeof JobsIdApplyRoute
}

const JobsIdRouteChildren: JobsIdRouteChildren = {
  JobsIdApplyRoute: JobsIdApplyRoute,
}

const JobsIdRouteWithChildren =
  JobsIdRoute._addFileChildren(JobsIdRouteChildren)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRouteWithChildren
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRouteWithChildren,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IntakeRoute: IntakeRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  ApplyReceivedApplicationIdRoute: ApplyReceivedApplicationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
