/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as IntakeConfirmationRouteImport } from './routes/intake.confirmation'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as JobsIdApplyRouteImport } from './routes/jobs.$id.apply'
import { Route as ApplyReceivedApplicationIdRouteImport } from './routes/apply.received.$applicationId'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPublishRouteImport } from './routes/_authenticated/admin.publish'
import { Route as AuthenticatedAdminHealthRouteImport } from './routes/_authenticated/admin.health'
import { Route as AuthenticatedAdminClientsRouteImport } from './routes/_authenticated/admin.clients'
import { Route as AuthenticatedAdminCandidatesRouteImport } from './routes/_authenticated/admin.candidates'
import { Route as AuthenticatedAdminPositionsIdRouteImport } from './routes/_authenticated/admin.positions.$id'
import { Route as AuthenticatedAdminClientsIdRouteImport } from './routes/_authenticated/admin.clients.$id'
import { Route as AuthenticatedAdminCandidatesIdRouteImport } from './routes/_authenticated/admin.candidates.$id'

const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const IntakeConfirmationRoute = IntakeConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => IntakeRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const JobsIdApplyRoute = JobsIdApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => JobsIdRoute,
} as any)
const ApplyReceivedApplicationIdRoute =
  ApplyReceivedApplicationIdRouteImport.update({
    id: '/apply/received/$applicationId',
    path: '/apply/received/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPublishRoute =
  AuthenticatedAdminPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHealthRoute =
  AuthenticatedAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsRoute =
  AuthenticatedAdminClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCandidatesRoute =
  AuthenticatedAdminCandidatesRouteImport.update({
    id: '/candidates',
    path: '/candidates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPositionsIdRoute =
  AuthenticatedAdminPositionsIdRouteImport.update({
    id: '/positions/$id',
    path: '/positions/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClientsIdRoute =
  AuthenticatedAdminClientsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminClientsRoute,
  } as any)
const AuthenticatedAdminCandidatesIdRoute =
  AuthenticatedAdminCandidatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCandidatesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/intake': typeof IntakeRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/intake/confirmation': typeof IntakeConfirmationRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/admin/candidates': typeof AuthenticatedAdminCandidatesRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/publish': typeof AuthenticatedAdminPublishRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/apply/received/$applicationId': typeof ApplyReceivedApplicationIdRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/candidates/$id': typeof AuthenticatedAdminCandidatesIdRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/positions/$id': typeof AuthenticatedAdminPositionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/intake': typeof IntakeRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/intake/confirmation': typeof IntakeConfirmationRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/admin/candidates': typeof AuthenticatedAdminCandidatesRouteWithChildren
  '/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/publish': typeof AuthenticatedAdminPublishRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/apply/received/$applicationId': typeof ApplyReceivedApplicationIdRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/candidates/$id': typeof AuthenticatedAdminCandidatesIdRoute
  '/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/admin/positions/$id': typeof AuthenticatedAdminPositionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/intake': typeof IntakeRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/intake/confirmation': typeof IntakeConfirmationRoute
  '/jobs/$id': typeof JobsIdRouteWithChildren
  '/_authenticated/admin/candidates': typeof AuthenticatedAdminCandidatesRouteWithChildren
  '/_authenticated/admin/clients': typeof AuthenticatedAdminClientsRouteWithChildren
  '/_authenticated/admin/health': typeof AuthenticatedAdminHealthRoute
  '/_authenticated/admin/publish': typeof AuthenticatedAdminPublishRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/apply/received/$applicationId': typeof ApplyReceivedApplicationIdRoute
  '/jobs/$id/apply': typeof JobsIdApplyRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/candidates/$id': typeof AuthenticatedAdminCandidatesIdRoute
  '/_authenticated/admin/clients/$id': typeof AuthenticatedAdminClientsIdRoute
  '/_authenticated/admin/positions/$id': typeof AuthenticatedAdminPositionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/intake'
    | '/jobs'
    | '/admin'
    | '/intake/confirmation'
    | '/jobs/$id'
    | '/admin/candidates'
    | '/admin/clients'
    | '/admin/health'
    | '/admin/publish'
    | '/admin/settings'
    | '/apply/received/$applicationId'
    | '/jobs/$id/apply'
    | '/admin/'
    | '/admin/candidates/$id'
    | '/admin/clients/$id'
    | '/admin/positions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/intake'
    | '/jobs'
    | '/intake/confirmation'
    | '/jobs/$id'
    | '/admin/candidates'
    | '/admin/clients'
    | '/admin/health'
    | '/admin/publish'
    | '/admin/settings'
    | '/apply/received/$applicationId'
    | '/jobs/$id/apply'
    | '/admin'
    | '/admin/candidates/$id'
    | '/admin/clients/$id'
    | '/admin/positions/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/intake'
    | '/jobs'
    | '/_authenticated/admin'
    | '/intake/confirmation'
    | '/jobs/$id'
    | '/_authenticated/admin/candidates'
    | '/_authenticated/admin/clients'
    | '/_authenticated/admin/health'
    | '/_authenticated/admin/publish'
    | '/_authenticated/admin/settings'
    | '/apply/received/$applicationId'
    | '/jobs/$id/apply'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/candidates/$id'
    | '/_authenticated/admin/clients/$id'
    | '/_authenticated/admin/positions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IntakeRoute: typeof IntakeRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  ApplyReceivedApplicationIdRoute: typeof ApplyReceivedApplicationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/intake/confirmation': {
      id: '/intake/confirmation'
      path: '/confirmation'
      fullPath: '/intake/confirmation'
      preLoaderRoute: typeof IntakeConfirmationRouteImport
      parentRoute: typeof IntakeRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/jobs/$id/apply': {
      id: '/jobs/$id/apply'
      path: '/apply'
      fullPath: '/jobs/$id/apply'
      preLoaderRoute: typeof JobsIdApplyRouteImport
      parentRoute: typeof JobsIdRoute
    }
    '/apply/received/$applicationId': {
      id: '/apply/received/$applicationId'
      path: '/apply/received/$applicationId'
      fullPath: '/apply/received/$applicationId'
      preLoaderRoute: typeof ApplyReceivedApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/publish': {
      id: '/_authenticated/admin/publish'
      path: '/publish'
      fullPath: '/admin/publish'
      preLoaderRoute: typeof AuthenticatedAdminPublishRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/health': {
      id: '/_authenticated/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthenticatedAdminHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients': {
      id: '/_authenticated/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/candidates': {
      id: '/_authenticated/admin/candidates'
      path: '/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AuthenticatedAdminCandidatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/positions/$id': {
      id: '/_authenticated/admin/positions/$id'
      path: '/positions/$id'
      fullPath: '/admin/positions/$id'
      preLoaderRoute: typeof AuthenticatedAdminPositionsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/clients/$id': {
      id: '/_authenticated/admin/clients/$id'
      path: '/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientsIdRouteImport
      parentRoute: typeof AuthenticatedAdminClientsRoute
    }
    '/_authenticated/admin/candidates/$id': {
      id: '/_authenticated/admin/candidates/$id'
      path: '/$id'
      fullPath: '/admin/candidates/$id'
      preLoaderRoute: typeof AuthenticatedAdminCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedAdminCandidatesRoute
    }
  }
}

interface AuthenticatedAdminCandidatesRouteChildren {
  AuthenticatedAdminCandidatesIdRoute: typeof AuthenticatedAdminCandidatesIdRoute
}

const AuthenticatedAdminCandidatesRouteChildren: AuthenticatedAdminCandidatesRouteChildren =
  {
    AuthenticatedAdminCandidatesIdRoute: AuthenticatedAdminCandidatesIdRoute,
  }

const AuthenticatedAdminCandidatesRouteWithChildren =
  AuthenticatedAdminCandidatesRoute._addFileChildren(
    AuthenticatedAdminCandidatesRouteChildren,
  )

interface AuthenticatedAdminClientsRouteChildren {
  AuthenticatedAdminClientsIdRoute: typeof AuthenticatedAdminClientsIdRoute
}

const AuthenticatedAdminClientsRouteChildren: AuthenticatedAdminClientsRouteChildren =
  {
    AuthenticatedAdminClientsIdRoute: AuthenticatedAdminClientsIdRoute,
  }

const AuthenticatedAdminClientsRouteWithChildren =
  AuthenticatedAdminClientsRoute._addFileChildren(
    AuthenticatedAdminClientsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCandidatesRoute: typeof AuthenticatedAdminCandidatesRouteWithChildren
  AuthenticatedAdminClientsRoute: typeof AuthenticatedAdminClientsRouteWithChildren
  AuthenticatedAdminHealthRoute: typeof AuthenticatedAdminHealthRoute
  AuthenticatedAdminPublishRoute: typeof AuthenticatedAdminPublishRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPositionsIdRoute: typeof AuthenticatedAdminPositionsIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCandidatesRoute:
    AuthenticatedAdminCandidatesRouteWithChildren,
  AuthenticatedAdminClientsRoute: AuthenticatedAdminClientsRouteWithChildren,
  AuthenticatedAdminHealthRoute: AuthenticatedAdminHealthRoute,
  AuthenticatedAdminPublishRoute: AuthenticatedAdminPublishRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPositionsIdRoute: AuthenticatedAdminPositionsIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface IntakeRouteChildren {
  IntakeConfirmationRoute: typeof IntakeConfirmationRoute
}

const IntakeRouteChildren: IntakeRouteChildren = {
  IntakeConfirmationRoute: IntakeConfirmationRoute,
}

const IntakeRouteWithChildren =
  IntakeRoute._addFileChildren(IntakeRouteChildren)

interface JobsIdRouteChildren {
  JobsIdApplyRoute: typeof JobsIdApplyRoute
}

const JobsIdRouteChildren: JobsIdRouteChildren = {
  JobsIdApplyRoute: JobsIdApplyRoute,
}

const JobsIdRouteWithChildren =
  JobsIdRoute._addFileChildren(JobsIdRouteChildren)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRouteWithChildren
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRouteWithChildren,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IntakeRoute: IntakeRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  ApplyReceivedApplicationIdRoute: ApplyReceivedApplicationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
