CREATE OR REPLACE VIEW public.v_admin_candidate_index AS
 SELECT m.id AS match_id,
    m.application_id,
    m.candidate_profile_id,
    m.position_id,
    m.organization_id,
    o.name AS org_name,
    p.title AS position_title,
    cp.full_name,
    cp.email,
    cp.phone,
    cp.country,
    cp.region,
    cp.city,
    cp.location,
    m.stage::text AS stage,
    m.admin_status::text AS admin_status,
    m.canonical_state::text AS canonical_state,
    m.client_visibility::text AS client_visibility,
    m.processing_state::text AS processing_state,
    m.eligibility_status::text AS eligibility_status,
    m.recommendation::text AS recommendation,
    m.integrity_status::text AS integrity_status,
    m.evidence_confidence,
    m.contact_released_at,
    m.contact_released_at IS NOT NULL AS contact_released,
    m.created_at,
    m.updated_at,
    a.applied_at,
    a.source,
    a.source_kind::text AS source_kind,
    a.source_channel,
    sr.id AS score_run_id,
    sr.score,
    sr.final_score,
    sr.fit_label,
    sr.fit_band,
    sr.confidence,
    sr.contradiction_status,
    score_band(COALESCE(sr.final_score, sr.score))::text AS score_band,
    m.integrity_status::text <> 'ok'::text OR (sr.contradiction_status = ANY (ARRAY['disqualifying_answer'::text, 'contradiction_found'::text])) OR m.eligibility_status::text = 'ineligible'::text OR (m.processing_state::text = ANY (ARRAY['failed'::text, 'provider_blocked'::text, 'manual_review_required'::text, 'ocr_required'::text])) AS has_critical_flag,
    lower((((((((((((COALESCE(cp.full_name, ''::text) || ' '::text) || COALESCE(cp.email, ''::text)) || ' '::text) || COALESCE(cp.phone, ''::text)) || ' '::text) || COALESCE(p.title, ''::text)) || ' '::text) || COALESCE(o.name, ''::text)) || ' '::text) || COALESCE(cp.city, ''::text)) || ' '::text) || COALESCE(cp.country, ''::text)) AS search_text,
    sr.completed_at AS scored_at,
    sr.engine_version AS scored_engine_version,
    sr.input_hash AS scored_input_hash,
    cp.updated_at AS profile_updated_at,
    p.updated_at AS brief_updated_at
   FROM candidate_matches m
     JOIN positions p ON p.id = m.position_id
     JOIN organizations o ON o.id = m.organization_id
     LEFT JOIN candidate_profiles cp ON cp.id = m.candidate_profile_id
     LEFT JOIN applications a ON a.id = m.application_id
     LEFT JOIN score_runs sr ON sr.id = COALESCE(m.approved_score_run_id, m.current_score_run_id);