update public.candidate_evidence_items e
set source_passage = m.txt
from (values
($q$Summary Sales professional with 3 years of B2B experience selling logistics services, plus…$q$,array['feb097e5']),
($q$Seeking to move fully into new-business sales management.$q$,array['3407146c','4c13b809','06121c8a']),
($q$Summary Customer success manager with 6 years of experience, including 2 years of expansion and renewal…$q$,array['be1c45e4']),
($q$Summary Customer success manager with 6 years of experience, including 2 years of expansion and renewal selling.$q$,array['49a5cecf','e45f210f']),
($q$Account Coordinator — Bright Harbor Media, Chicago, IL Skills Renewal and expansion selling; relationship management; negotiation;…$q$,array['478a5363']),
($q$Summary Sales professional with 3 years of B2B experience selling logistics services, plus 2 years in retail…$q$,array['f22d7e2b']),
($q$3 years of B2B experience selling logistics services, plus 2 years in retail management. Quota attainment between 88% and 106%.$q$,array['cd4d9216']),
($q$…in retail management. Quota attainment between 88% and 106%.$q$,array['cc7c88f5']),
($q$Summary Sales professional with 3 years of B2B experience selling logistics services, plus 2 years in retail management.$q$,array['8c038191']),
($q$Used HubSpot for pipeline tracking and weekly forecast submission.$q$,array['61773399']),
($q$Skills Cold calling; freight and logistics sales; negotiation; HubSpot; account…$q$,array['b7d6ff70']),
($q$Summary Marketing generalist with 5 years of B2B demand-generation experience.$q$,array['fafa8697']),
($q$Experience Demand Generation Manager — Northbridge Analytics, Chicago, IL (2022 - present) Ran paid and email…$q$,array['cb45e9cb']),
($q$Grace Whitfield Chicago, IL$q$,array['bdb3b4dd']),
($q$Strong communication and CRM skills; exploring a move into sales.$q$,array['8ccd11b2','c581fb16','5ea8fba0']),
($q$Chicago resident. No quota-carrying sales experience and no closing track record.$q$,array['0425d27c']),
($q$Summary Retail and hospitality operations manager with 8 years of leadership experience. Looking for a career change into sales management.$q$,array['2e0886dd']),
($q$Summary Retail and hospitality operations manager with 8 years of leadership experience.$q$,array['8cdea38e']),
($q$Looking for a career change into sales management.$q$,array['b5dfe84c','4f6b862e','34ec0eb3','8de65183']),
($q$Handled vendor negotiations, scheduling, payroll and P&L; reporting.$q$,array['3a81c9f1']),
($q$Paulo, Brazil Summary Inside sales representative with 2 years of experience selling telecom packages to small…$q$,array['f041666e','1c5a1506','99f0cb40']),
($q$…representative with 2 years of experience selling telecom packages to small businesses in Brazil. Seeking an international opportunity.$q$,array['713ffd5e']),
($q$Summary Inside sales representative with 2 years of experience selling telecom packages to small businesses in Brazil.$q$,array['f30f15f3']),
($q$Logged activity in a proprietary internal CRM.$q$,array['bb374626']),
($q$Skills Telephone sales; customer service; Portuguese (native); Spanish (fluent);…$q$,array['a3af9a92']),
($q$Profile Full-stack engineer with 10 years of professional experience.$q$,array['ae73cc1c']),
($q$…flags and a full regression suite. Delivered in phases with no downtime.$q$,array['e12f46e1','836d3487','3ae62b34','18c1dfa1','4d5f2999','8903cd0c','e71f08d7','b0eef3a6','7aa5a850','63ead51a','a672fa06','3d6f5f86','87cf344a','8bf4c437','b8d701e8','4f8ab799','3e3c2444','2f167574','fe235671']),
($q$Core stack: TypeScript, React, Next.js, Node.js, PostgreSQL.$q$,array['f1d091e8','099bcf92','26b5352e','a7174df9']),
($q$Engineering — Universidade do Porto Languages Portuguese (native), English (C2), French (B1) References Available on request.$q$,array['4955504e']),
($q$Full-Stack Engineer — Duna Labs, Braga 2014-09 to 2016-09 React/Node product work for early-stage clients.$q$,array['6ebbdc04']),
($q$Sofia Marques Staff-level Full-Stack Engineer — TypeScript everywhere Porto,…$q$,array['d5000f51']),
($q$Profile Full-stack engineer with 7 years of professional experience.$q$,array['02592658','cafcd490']),
($q$Core stack: React, TypeScript, Node.js, PostgreSQL, AWS.$q$,array['a73540e3','a2224953','59c4c50b','3242cf43','9b26ef5a','55c4a8e2','b42700fe','3034b256']),
($q$BSc Computer Engineering — NOVA FCT Languages Portuguese (native), English (C1) References Available on request.$q$,array['08e4a6c6']),
($q$Selected projects Platform rebuild — Rebuilt a customer-facing product in React with a typed API layer, feature flags and a full regression suite.$q$,array['39e10165','ab2a524d']),
($q$Tiago Almeida Full-Stack Engineer — React, Node.js, PostgreSQL Lisbon,…$q$,array['c45bf4ce']),
($q$Profile Full-stack engineer with 6 years of professional experience.$q$,array['a4fd64bd']),
($q$Core stack: React, TypeScript, Node.js, PostgreSQL, GCP.$q$,array['d8304ce2','b2454cde','7bb3dfc2','0d14a9e1']),
($q$Science — Universidade de Lisboa Languages Portuguese (native), English (B2) References Available on request.$q$,array['f1ac99ef']),
($q$Stack Engineer — Trilho Software, Lisbon 2021-03 to present React + TypeScript product work with Node.js services and PostgreSQL, deployed on Google Cloud Run.$q$,array['6ba894ff']),
($q$Rui Fernandes Full-Stack Engineer — React, Node.js (cloud on GCP) Lisbon,…$q$,array['c230999a']),
($q$Profile Full-stack engineer with 9 years of professional experience.$q$,array['3a911996','64550a44']),
($q$Core stack: TypeScript, React, Node.js, PostgreSQL, AWS.$q$,array['934bd950','abfcad82','220cbf2c','89df68e9','72fd316c','09a6f4a4','8a8719af','97a1783c']),
($q$BSc Information Systems — ISCTE Languages Portuguese (native), English (C2) References Available on request.$q$,array['7ec27b7e']),
($q$Beatriz Costa Senior Full-Stack Engineer — product-focused, TypeScript/AWS Lisbon, Portugal…$q$,array['3c911437']),
($q$Beatriz Costa Senior Full-Stack Engineer — product-focused, TypeScript/AWS Lisbon,…$q$,array['32279315']),
($q$Profile Full-stack engineer with 4 years of professional experience.$q$,array['f601dfb8']),
($q$Core stack: React, JavaScript, Node.js, MongoDB, Docker.$q$,array['bea29d97','a89093c8','c5cf26fe','eb3c6755']),
($q$…degree, Web Development — ATEC Languages Portuguese (native), English (B2) References Available on request.$q$,array['a57e46fb']),
($q$React front ends and Node.js/Express APIs with MongoDB; limited TypeScript exposure and no cloud ownership.$q$,array['09888e4f']),
($q$Diogo Silva Full-Stack Developer — React and Node.js Lisbon,…$q$,array['c96e6edb']),
($q$Profile Full-stack engineer with 2 years of professional experience.$q$,array['a2e009db']),
($q$Core stack: PHP, WordPress, jQuery, MySQL, HTML/CSS.$q$,array['2f4cded5','60a261fa','75910a70','13c79367']),
($q$— Escola Profissional de Lisboa Languages Portuguese (native), English (B1) References Available on request.$q$,array['77ec2d6f']),
($q$Selected projects Platform rebuild — Rebuilt a customer-facing product in PHP with a typed API layer, feature flags and a full regression suite.$q$,array['bb3d7a99']),
($q$Lisbon, Portugal Profile Full-stack engineer with 2 years of professional experience.$q$,array['62e4ac52']),
($q$Profile Full-stack engineer with 5 years of professional experience.$q$,array['848d229f']),
($q$Core stack: Vue.js, JavaScript, TypeScript, Node.js, PostgreSQL.$q$,array['8c10ab2b','f2292ce6','293c413b']),
($q$Comfortable owning features end to end, from database schema through API to interface,…$q$,array['3d169211']),
($q$— Universidad Politécnica de Madrid Languages Spanish (native), English (C1), Portuguese (A2) References Available on request.$q$,array['afea90f6']),
($q$Selected projects Platform rebuild — Rebuilt a customer-facing product in Vue.js with a typed API layer, feature flags and a full regression suite.$q$,array['69534f60']),
($q$Inês Lopes Full-Stack Engineer — Vue moving to React Madrid, Spain…$q$,array['8e72fad2']),
($q$— Instituto Superior Técnico Languages Portuguese (native), English (C2), Spanish (B2) References Available on request.$q$,array['0c30079f']),
($q$Ana Ribeiro Senior Full-Stack Engineer — React, TypeScript, Node.js Lisbon,…$q$,array['85e53112']),
($q$Profile Full-stack engineer with 8 years of professional experience.$q$,array['4d1ae84b']),
($q$— Universidade de Coimbra Languages Portuguese (native), English (C1) References Available on request.$q$,array['36d8c5cf']),
($q$Selected projects Platform rebuild — Rebuilt a customer-facing product in…$q$,array['de398d2e']),
($q$Selected projects Platform rebuild — Rebuilt a customer-facing product in TypeScript with a typed API layer, feature flags and a full regression…$q$,array['275894be']),
($q$Miguel Torres Senior Full-Stack Engineer — Node.js, React, AWS Lisbon,…$q$,array['3c0889f3']),
($q$Core stack: React, TypeScript, Node.js, GraphQL, MySQL.$q$,array['2e4d3afd','99f01ac0','99aad132','159165c9']),
($q$Engineering — Universidade do Minho Languages Portuguese (native), English (C1) References Available on request.$q$,array['0e702797']),
($q$Frontend Engineer — Nimbo Apps, Braga 2018-05 to 2020-08 React and React Native product work, some Node.js BFF services on AWS.$q$,array['b8314faa']),
($q$Carla Nunes Senior Frontend-leaning Full-Stack Engineer (remote-first) Braga, Portugal…$q$,array['3710e404'])
) as m(txt, id_prefixes)
where left(e.id::text, 8) = any (m.id_prefixes);